spring.application.name=Finder

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/finder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# run one `create` -> then switch to `update` or `validate`