spring.application.name=Finder
spring.datasource.url=jdbc:mysql://localhost:3306/finder
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.base-path=/api
spring.data.rest.default-page-size=10
springdoc.swagger-ui.path=/swagger
